server:
  port: 8080
spring:
  application:
    name: "JavaImperativeMS"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
spring.datasource.url: "jdbc:postgresql://${DATABASE_IP:db}:5432/compose-postgres"
spring.datasource.username: "compose-postgres"
spring.datasource.password: "compose-postgres"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"

spring.datasource.hikari.maximum-pool-size: 10

adapter:
  restconsumer:
    url: "http://${EXTERNAL_SERVICE_IP:node-latency}:8080"
